In [4]:
import numpy as np 
import matplotlib.pyplot as plt
import tensorflow as tf
# necessary package for DL is already installed

In [5]:
# Ndarray Object
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [10]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [12]:
c = np.array([1, 2, 3, 4, 5], ndmin = 2)
print(c)

[[1 2 3 4 5]]


In [14]:
d = np.array([1, 2, 3, 4, 5], dtype = complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [16]:
# type of ndarray
dt = np.dtype(np.int32)
print(dt)
dt = np.dtype(np.int)
print(dt)

int32
int64


In [17]:
# 创建结构化数据类型
dt = np.dtype([('age', np.int8)])
print(dt)

[('age', 'i1')]


In [19]:
e = np.array([(10, ), (20, ), (30, )], dtype = dt)
print(e)
print(e['age'])

[(10,) (20,) (30,)]
[10 20 30]


In [21]:
# create array
a = np.arange(24)
print(a.ndim)
# adjust size
b = a.reshape(3, 8)
print(b.ndim)
# ndim是矩阵的维度，相当于秩

1
2


In [23]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.shape)
# 2 rows and 3 columns

(2, 3)


In [26]:
a.shape = (3, 2)
print(a)
a = a.reshape(2, 3)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [27]:
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


In [52]:
# create array
# number is uncertained
# both () and [] are ok
x = np.empty([3, 2], dtype = int)
print(x)
y = np.zeros([3, 2]) # default is float
print(y)
z = np.zeros((3, 2), dtype = int)
print(z)

[[0 0]
 [0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]]


In [53]:
x = np.ones(5) 
print(x)
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


In [56]:
# covert existing python data type to ndarray
x = [1, 2, 3]
a = np.asarray(x)
print(x)
print(a)

x = (1, 2, 3)
a = np.asarray(x)
print(x)
print(a)

x = ((1, 2, 3), (4, 5, 6))
a = np.asarray(x)
print(x)
print(a)

[1, 2, 3]
[1 2 3]
(1, 2, 3)
[1 2 3]
((1, 2, 3), (4, 5, 6))
[[1 2 3]
 [4 5 6]]


In [64]:
a = np.array(range(1,10))
a = a.reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [68]:
# numpy linspace
a = np.linspace(1, 10, num=10, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [70]:
# numpy logspace
a = np.logspace(1.0, 20.0, num=10)
print(a)

[1.00000000e+01 1.29154967e+03 1.66810054e+05 2.15443469e+07
 2.78255940e+09 3.59381366e+11 4.64158883e+13 5.99484250e+15
 7.74263683e+17 1.00000000e+20]


In [71]:
# ndarray advance 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


In [79]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a)
print(a[0:2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5]


In [80]:
# broadcast
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [81]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print(a + bb)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [82]:
a = np.arange(12).reshape(3,4)

print(a)

print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [90]:
import numpy.matlib 
import numpy as np
 
print (np.matlib.empty((2,2)))

[[6.95332964e-310 0.00000000e+000]
 [0.00000000e+000 2.12199579e-313]]


In [107]:
# randn return Gaussian ditribution
a = np.random.randn(9).reshape(3, 3)
print(a)
# rand return uniform distribution
b = np.random.rand(9).reshape(3, 3)
print(b)

# test validity
c = np.random.rand(1000000).sum()
print(c / 1000000)
d = np.random.randn(1000000).sum()
print(d / 1000000)

[[-0.93274021  0.15896053 -1.15530272]
 [ 1.00482968  0.79221666  0.13878599]
 [-0.15039098 -0.92860157  0.28437963]]
[[0.52826512 0.19074181 0.18489389]
 [0.9422412  0.11325064 0.73185146]
 [0.95177537 0.02339372 0.13697869]]
0.5000033679584325
0.0008764924526800507


In [110]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)
print(a)
print(b)
print(np.dot(a, b.T))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [111]:
a = np.array([[1,2], [3,4]]) 
print ('数组 a：')
print (a)
b = np.array([[11, 12], [13, 14]]) 
print ('数组 b：')
print (b)
 
print ('内积：')
print (np.inner(a,b))

数组 a：
[[1 2]
 [3 4]]
数组 b：
[[11 12]
 [13 14]]
内积：
[[35 41]
 [81 95]]
